"""init

Revision ID: 78a33ea3220d
Revises: 
Create Date: 2023-02-23 02:46:35.964417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a33ea3220d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprise',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_enterprise_uuid'), 'enterprise', ['uuid'], unique=False)
    op.create_table('executed_transaction',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('transaction', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('transaction')
    )
    op.create_index(op.f('ix_executed_transaction_uuid'), 'executed_transaction', ['uuid'], unique=False)
    op.create_table('user',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('login')
    )
    op.create_index(op.f('ix_user_uuid'), 'user', ['uuid'], unique=False)
    op.create_table('execution_traffic',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('traffic', sa.String(), nullable=True),
    sa.Column('transaction', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['transaction'], ['executed_transaction.transaction'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_execution_traffic_uuid'), 'execution_traffic', ['uuid'], unique=False)
    op.create_table('research',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('laboratory', sa.String(), nullable=True),
    sa.Column('disease', sa.String(), nullable=True),
    sa.Column('date_of_research', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('expertise_id', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('conclusion', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('enterprise_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['enterprise_name'], ['enterprise.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_research_uuid'), 'research', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_uuid'), table_name='research')
    op.drop_table('research')
    op.drop_index(op.f('ix_execution_traffic_uuid'), table_name='execution_traffic')
    op.drop_table('execution_traffic')
    op.drop_index(op.f('ix_user_uuid'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_executed_transaction_uuid'), table_name='executed_transaction')
    op.drop_table('executed_transaction')
    op.drop_index(op.f('ix_enterprise_uuid'), table_name='enterprise')
    op.drop_table('enterprise')
    # ### end Alembic commands ###
